# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/iamako/Documents/CHPS0801/projet/Stencil-Kokkos-OpenMP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/iamako/Documents/CHPS0801/projet/Stencil-Kokkos-OpenMP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iamako/Documents/CHPS0801/projet/Stencil-Kokkos-OpenMP/CMakeFiles /home/iamako/Documents/CHPS0801/projet/Stencil-Kokkos-OpenMP//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/iamako/Documents/CHPS0801/projet/Stencil-Kokkos-OpenMP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stencil_kokkos.exe

# Build rule for target.
stencil_kokkos.exe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stencil_kokkos.exe
.PHONY : stencil_kokkos.exe

# fast build rule for target.
stencil_kokkos.exe/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stencil_kokkos.exe.dir/build.make CMakeFiles/stencil_kokkos.exe.dir/build
.PHONY : stencil_kokkos.exe/fast

stencil_kokkos.o: stencil_kokkos.cpp.o
.PHONY : stencil_kokkos.o

# target to build an object file
stencil_kokkos.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stencil_kokkos.exe.dir/build.make CMakeFiles/stencil_kokkos.exe.dir/stencil_kokkos.cpp.o
.PHONY : stencil_kokkos.cpp.o

stencil_kokkos.i: stencil_kokkos.cpp.i
.PHONY : stencil_kokkos.i

# target to preprocess a source file
stencil_kokkos.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stencil_kokkos.exe.dir/build.make CMakeFiles/stencil_kokkos.exe.dir/stencil_kokkos.cpp.i
.PHONY : stencil_kokkos.cpp.i

stencil_kokkos.s: stencil_kokkos.cpp.s
.PHONY : stencil_kokkos.s

# target to generate assembly for a file
stencil_kokkos.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stencil_kokkos.exe.dir/build.make CMakeFiles/stencil_kokkos.exe.dir/stencil_kokkos.cpp.s
.PHONY : stencil_kokkos.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... stencil_kokkos.exe"
	@echo "... stencil_kokkos.o"
	@echo "... stencil_kokkos.i"
	@echo "... stencil_kokkos.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

